- name: Include GitHub release version check
  ansible.builtin.include_tasks: common/github_release.yml
  vars:
    binary_name: trivy
    repo: aquasecurity/trivy
    version_check_command: trivy version
    version_pattern: v([0-9]+\.){2}[0-9]+
    add_v_prefix: true

- name: Set trivy architecture
  set_fact:
    trivy_arch: "{{ 'ARM64' if arch == 'arm64' else '64bit' }}"

- name: Download, extract and install trivy
  when: current_trivy_version | default('none') != trivy_version
  become: true
  unarchive:
    # https://github.com/aquasecurity/trivy/releases/download/v0.69.1/trivy_0.69.1_Linux-64bit.tar.gz
    src: "https://github.com/aquasecurity/trivy/releases/download/{{ trivy_version }}/trivy_{{ trivy_version | regex_replace('^v', '') }}_Linux-{{ trivy_arch }}.tar.gz"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
    # The specific file(s) to extract
    - trivy
